### ISSUE TITLE
Create a homepage in GitHub Pages

### ISSUE THREAD

**Issue by order-desk** [order-desk/hacktoberfest2022#1]
The selected theme should have a landing page. Blocked by #26

**Comment by abhishekpatil4** [comment]
@order-desk Assign me this task, will get it done in no time

**Comment by order-desk** [comment]
Hi @abhishekpatil4, you've stumbled into a project that we're running internally with our company. As outlined in [CONTRIBUTING.md](https://github.com/order-desk/hacktoberfest2022/blob/main/CONTRIBUTING.md), requests from outside our organization will be rejected. Apologies!
