### ISSUE TITLE
Add the Order Desk logo to the homepage

### ISSUE THREAD

**Issue by order-desk** [order-desk/hacktoberfest2022#14]

**Comment by DevTomilola-OS** [comment]
Kindly assign to me.

**Comment by ekinhbayar** [comment]
@slouieod seeing you were interested in uploading the hacktoberfest logo to the homepage, I thought you might want to take on this one to use Order Desk logo on the [Order Desk hacktoberfest website](https://order-desk.github.io/hacktoberfest2022/)

To do so you can visit https://github.com/order-desk/hacktoberfest2022/tree/main/example/images - click the Add file button to upload logo.png. Then, you can "Create a new branch for this commit and start a pull request." to upload the site logo. Let me know if you need help.

**Comment by slouieod** [comment]
@danschenker per Ekin's note, I'll take this one as well :)
