### ISSUE TITLE
Add Hacktoberfest logo to homepage

### ISSUE THREAD

**Issue by order-desk** [order-desk/hacktoberfest2022#15]

**Comment by slouieod** [comment]
I can take this one!

**Comment by ekinhbayar** [comment]
@slouieod you can visit https://github.com/order-desk/hacktoberfest2022/tree/main/example/images - click the Add file button to upload logo.png. Then, you can "Create a new branch for this commit and start a pull request." to upload the site logo. Let me know if you need help.

**Comment by invarrow** [comment]
is this still open? If yes where do you want the logo?

**Comment by danschenker** [comment]
> is this still open? If yes where do you want the logo?

Please review [CONTRIBUTING.md](https://github.com/order-desk/hacktoberfest2022/blob/main/CONTRIBUTING.md), and best of luck completing Hacktoberfest 2022!
