### ISSUE TITLE
Compare, contrast, and ultimately select theme for our journal page

### ISSUE THREAD

**Issue by order-desk** [order-desk/hacktoberfest2022#26]
For the quickest way of seeing what you change inside this repository, we have enabled GitHub Pages, which, like WP, has themes that you can pick and set up. https://github.com/topics/github-pages there's a whole bunch of them out there. Let's pick one keeping in mind the kind of contributions that are being worked on.

**Comment by slouieod** [comment]
I'd be happy to take this one on as well!

**Comment by danschenker** [comment]
> I'd be happy to take this one on as well!

It's yours!

**Comment by danschenker** [comment]
> It looks to me like this specific theme should be a good match for the different kinds of content we're producing in this Hacktoberfest.
> 
> https://github.com/mmistakes/so-simple-theme

Looks good to me. If you update [contributions.md](https://github.com/order-desk/hacktoberfest2022/blob/main/contributions.md) and submit a PR, I'll merge it in.

@ekinhbayar can you please add this theme to our journal page?

**Comment by ekinhbayar** [comment]
I've assigned this on me through issue #29, will track the installation there. Thanks!
